INSERT INTO products.items (name, category, price) VALUES ('Item #1', 'Profit goods', 2000);
INSERT INTO products.items (name, category, price) VALUES ('Item #2', 'Profit goods', 12000);
INSERT INTO products.items (name, category, price) VALUES ('Item #3', 'Profit goods', 23000);
INSERT INTO products.items (name, category, price) VALUES ('Item #4', 'Trinkets', 5000);
INSERT INTO products.items (name, category, price) VALUES ('Item #5', 'Profit goods', 15000);
INSERT INTO products.items (name, category, price) VALUES ('Item #6', 'Profit goods', 4000);
INSERT INTO products.items (name, category, price) VALUES ('Item #7', 'Profit goods', 17000);
INSERT INTO products.items (name, category, price) VALUES ('Item #8', 'Trinkets', 17000);
INSERT INTO products.items (name, category, price) VALUES ('Item #9', 'Profit goods', 10000);
INSERT INTO products.items (name, category, price) VALUES ('Item #10', 'Profit goods', 16000);
INSERT INTO products.items (name, category, price) VALUES ('Item #11', 'Profit goods', 22000);
INSERT INTO products.items (name, category, price) VALUES ('Item #12', 'Trinkets', 6000);
INSERT INTO products.items (name, category, price) VALUES ('Item #13', 'Profit goods', 1000);
INSERT INTO products.items (name, category, price) VALUES ('Item #14', 'Profit goods', 27000);
INSERT INTO products.items (name, category, price) VALUES ('Item #15', 'Trinkets', 14000);
INSERT INTO products.items (name, category, price) VALUES ('Item #16', 'Profit goods', 3000);
INSERT INTO products.items (name, category, price) VALUES ('Item #17', 'Profit goods', 4000);
INSERT INTO products.items (name, category, price) VALUES ('Item #18', 'Trinkets', 18000);
INSERT INTO products.items (name, category, price) VALUES ('Item #19', 'Profit goods', 5000);
INSERT INTO products.items (name, category, price) VALUES ('Item #20', 'Profit goods', 7000);
INSERT INTO products.items (name, category, price) VALUES ('Item #21', 'Trinkets', 25000);
INSERT INTO products.items (name, category, price) VALUES ('Item #22', 'Profit goods', 9000);
INSERT INTO products.items (name, category, price) VALUES ('Item #23', 'Profit goods', 11000);
INSERT INTO products.items (name, category, price) VALUES ('Item #24', 'Profit goods', 10000);
INSERT INTO products.items (name, category, price) VALUES ('Item #25', 'Trinkets', 28000);
INSERT INTO products.items (name, category, price) VALUES ('Item #26', 'Trinkets', 31000);
INSERT INTO products.items (name, category, price) VALUES ('Item #27', 'Trinkets', 40000);
INSERT INTO products.items (name, category, price) VALUES ('Item #28', 'Trinkets', 36000);
INSERT INTO products.items (name, category, price) VALUES ('Item #29', 'Profit goods', 24000);
INSERT INTO products.items (name, category, price) VALUES ('Item #30', 'Profit goods', 33000);
